#!/usr/bin/env python3
"""Flatten the @-import CLAUDE.md tree into a single ~/.agents/AGENTS.md.

PostHog Code's Personalization sync reads the first non-empty of
~/.agents/AGENTS.md, ~/.codex/AGENTS.md, ~/.claude/AGENTS.md, ~/.claude/CLAUDE.md
with a plain readFile: no @-import expansion, and it truncates at 20k chars. The
repo's CLAUDE.md is a thin stub of @-imports, so without this the sync ships the
stub and none of the real rules. Emitting a flattened ~/.agents/AGENTS.md wins
that candidate order and carries the full ruleset to local and cloud runs.
"""

import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(REPO_ROOT, "CLAUDE.md")
OUTPUT = os.path.expanduser("~/.agents/AGENTS.md")
CHAR_CAP = 20_000

IMPORT_RE = re.compile(r"^@(\S+)\s*$")

HEADER = (
    "<!-- Generated by dotfiles-ai install.sh; do not edit. "
    "Edit CLAUDE.md + claude/*.md and reinstall. -->\n\n"
)


def expand(path, seen):
    real = os.path.realpath(path)
    if real in seen:
        return f"<!-- skipped cyclic import: {os.path.relpath(path, REPO_ROOT)} -->\n"
    seen = seen | {real}
    base = os.path.dirname(path)
    out = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            match = IMPORT_RE.match(line)
            if match:
                out.append(expand(os.path.join(base, match.group(1)), seen))
            else:
                out.append(line)
    return "".join(out)


def strip_source_preamble(text):
    """Drop the CLAUDE.md symlink/@-import note that is meaningless once flattened."""
    lines = text.splitlines(keepends=True)
    kept = [
        line
        for line in lines
        if not line.startswith("> **Source**")
        and "loaded via" not in line
    ]
    return "".join(kept)


def collapse_blank_runs(text):
    return re.sub(r"\n{3,}", "\n\n", text)


def main():
    body = collapse_blank_runs(strip_source_preamble(expand(SOURCE, frozenset())))
    content = HEADER + body.strip() + "\n"

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(content)

    count = len(content)
    if count > CHAR_CAP:
        print(
            f"[warn] {OUTPUT} is {count} chars; PostHog Code truncates at "
            f"{CHAR_CAP}. Trim the source files to avoid dropped rules.",
            file=sys.stderr,
        )
    print(f"wrote {OUTPUT} ({count} chars)")


if __name__ == "__main__":
    main()
