#!/usr/bin/env python3
"""Flatten personal instruction trees for PostHog Code and Codex.

PostHog Code's Personalization sync reads the first non-empty of
~/.agents/AGENTS.md, ~/.codex/AGENTS.md, ~/.claude/AGENTS.md, ~/.claude/CLAUDE.md
with a plain readFile: no @-import expansion, and it truncates at 20k chars. The
repo's CLAUDE.md is a thin stub of @-imports, so without this the sync ships the
stub and none of the real rules. Codex also needs a real ~/.codex/AGENTS.md;
unlike Claude Code, it does not expand @-imports. Generate both from the same
shared rules, with a Codex-specific root for client-specific behavior.
"""

import argparse
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUTS = (
    {
        "source": os.path.join(REPO_ROOT, "CLAUDE.md"),
        "output": os.path.expanduser("~/.agents/AGENTS.md"),
        "cap": 20_000,
        "warn_at": 18_000,
        "unit": "characters",
        "consumer": "PostHog Code",
    },
    {
        "source": os.path.join(REPO_ROOT, "codex/AGENTS.md"),
        "output": os.path.expanduser("~/.codex/AGENTS.md"),
        "cap": 65_536,
        "warn_at": 60_000,
        "unit": "bytes",
        "consumer": "Codex",
    },
)

IMPORT_RE = re.compile(r"^@(\S+)\s*$")

HEADER = "<!-- Generated by dotfiles-ai install.sh; do not edit. -->\n\n"


def source_lines(path):
    """Read a source, removing skill/output-style YAML frontmatter if present."""
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    if lines and lines[0].strip() == "---":
        for index, line in enumerate(lines[1:], start=1):
            if line.strip() == "---":
                return lines[index + 1 :]
    return lines


def expand(path, seen):
    real = os.path.realpath(path)
    if real in seen:
        return f"<!-- skipped cyclic import: {os.path.relpath(path, REPO_ROOT)} -->\n"
    seen = seen | {real}
    base = os.path.dirname(path)
    out = []
    for line in source_lines(path):
        match = IMPORT_RE.match(line)
        if match:
            out.append(expand(os.path.join(base, match.group(1)), seen))
        else:
            out.append(line)
    return "".join(out)


def strip_source_preamble(text):
    """Drop the CLAUDE.md symlink/@-import note that is meaningless once flattened."""
    lines = text.splitlines(keepends=True)
    kept = [
        line
        for line in lines
        if not line.startswith("> **Source**") and "loaded via" not in line
    ]
    return "".join(kept)


def collapse_blank_runs(text):
    return re.sub(r"\n{3,}", "\n\n", text)


def content_size(content, unit):
    return len(content) if unit == "characters" else len(content.encode("utf-8"))


def generate(spec):
    body = collapse_blank_runs(
        strip_source_preamble(expand(spec["source"], frozenset()))
    )
    content = HEADER + body.strip() + "\n"
    output = spec["output"]

    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w", encoding="utf-8") as f:
        f.write(content)

    count = content_size(content, spec["unit"])
    cap = spec["cap"]
    if count > cap:
        dropped = [
            heading
            for heading in re.findall(r"^# .+$", content, re.M)
            if content_size(content[: content.find(heading)], spec["unit"]) >= cap
        ]
        print(
            f"[warn] {output} is {count} {spec['unit']}; "
            f"{spec['consumer']} reads at most {cap}. Sections past the cut: "
            f"{', '.join(dropped) or 'tail of the last section'}.",
            file=sys.stderr,
        )
    elif count > spec["warn_at"]:
        print(
            f"[warn] {output} is {count} {spec['unit']}, within {cap - count} "
            f"of the {cap} cap. Trim before adding more rules.",
            file=sys.stderr,
        )
    print(f"wrote {output} ({count} {spec['unit']})")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--target",
        choices=("all", "posthog-code", "codex"),
        default="all",
    )
    args = parser.parse_args()

    for index, spec in enumerate(OUTPUTS):
        if args.target == "posthog-code" and index != 0:
            continue
        if args.target == "codex" and index != 1:
            continue
        generate(spec)


if __name__ == "__main__":
    main()
